name: Build Flipper App (Manual CMake)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential git python3-pip ninja-build

      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Clone Flipper Firmware
        run: |
          git clone --depth 1 https://github.com/flipperdevices/flipperzero-firmware.git

      - name: Copy app into firmware
        run: |
          mkdir -p flipperzero-firmware/applications_user/flipper_arrow
          cp *.c *.h CMakeLists.txt flipperzero-firmware/applications_user/flipper_arrow/

      - name: Build .fap
        run: |
          cd flipperzero-firmware
          ./fbt_tools/fbt fap_flipper_arrow

      - name: Upload .fap
        uses: actions/upload-artifact@v4
        with:
          name: flipper_arrow.fap
          path: flipperzero-firmware/build/f7-firmware-D/.extapps/flipper_arrow.fap