name: Build Flipper App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install ufbt
        run: |
          python3 -m pip install --upgrade pip
          pip install flipperzero-ufbt
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Clone Flipper firmware
        run: |
          git clone --depth 1 https://github.com/flipperdevices/flipperzero-firmware.git
          mkdir -p .ufbt
          echo "{\"firmware_path\": \"flipperzero-firmware\"}" > .ufbt/settings.json

      - name: Build .fap
        run: |
          ufbt fap

      - name: Upload .fap
        uses: actions/upload-artifact@v4
        with:
          name: flipper_arrow.fap
          path: build/f7-firmware-D/.extapps/*.fap