name: Build Flipper App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install uFBT (Flipper build tool)
        run: |
          python3 -m pip install --upgrade pip
          pip install flipperzero-ufbt

      - name: Add uFBT to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build app
        run: |
          ufbt init --firmware https://github.com/flipperdevices/flipperzero-firmware.git
          ufbt fap

      - name: Upload .fap file
        uses: actions/upload-artifact@v4
        with:
          name: flipper_arrow.fap
          path: build/f7-firmware-D/.extapps/*.fap