name: Build Flipper App (pure CMake)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential git ninja-build

      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Clone Flipper Firmware
        run: |
          git clone --depth 1 https://github.com/flipperdevices/flipperzero-firmware.git

      - name: Copy app into firmware
        run: |
          mkdir -p flipperzero-firmware/applications_user/flipper_arrow
          cp flipper_arrow.c music.c music.h flipperzero-firmware/applications_user/flipper_arrow/
          cp CMakeLists.txt flipperzero-firmware/applications_user/flipper_arrow/CMakeLists.txt
          echo 'add_subdirectory(flipper_arrow)' >> flipperzero-firmware/applications_user/CMakeLists.txt

      - name: Configure and build
        run: |
          cd flipperzero-firmware/firmware
          cmake -S . -B build -GNinja -DFLIPPER_TARGET=F7
          cmake --build build --target flipper_arrow

      - name: Upload .fap
        uses: actions/upload-artifact@v4
        with:
          name: flipper_arrow.fap
          path: flipperzero-firmware/firmware/build/.extapps/flipper_arrow.fap